# Generated by Django 4.2.3 on 2023-07-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('C', 'Caixa Economica'), ('BR', 'Bradesco'), ('BS', 'Banco do Brasil')], max_length=4),
        ),
    ]
